# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logincard.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(684, 316)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 791, 571))
        self.tabWidget.setObjectName("tabWidget")
        self.maintab = QtWidgets.QWidget()
        self.maintab.setObjectName("maintab")
        self.name_labe1 = QtWidgets.QLabel(self.maintab)
        self.name_labe1.setGeometry(QtCore.QRect(80, 80, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.name_labe1.setFont(font)
        self.name_labe1.setObjectName("name_labe1")
        self.btn_find_name = QtWidgets.QPushButton(self.maintab)
        self.btn_find_name.setGeometry(QtCore.QRect(280, 70, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_find_name.setFont(font)
        self.btn_find_name.setObjectName("btn_find_name")
        self.mobile_label = QtWidgets.QLabel(self.maintab)
        self.mobile_label.setGeometry(QtCore.QRect(50, 110, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mobile_label.setFont(font)
        self.mobile_label.setObjectName("mobile_label")
        self.mobile_show = QtWidgets.QLabel(self.maintab)
        self.mobile_show.setGeometry(QtCore.QRect(130, 110, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mobile_show.setFont(font)
        self.mobile_show.setObjectName("mobile_show")
        self.precard_label = QtWidgets.QLabel(self.maintab)
        self.precard_label.setGeometry(QtCore.QRect(70, 140, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.precard_label.setFont(font)
        self.precard_label.setObjectName("precard_label")
        self.precard_show = QtWidgets.QLabel(self.maintab)
        self.precard_show.setGeometry(QtCore.QRect(130, 140, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.precard_show.setFont(font)
        self.precard_show.setObjectName("precard_show")
        self.nowcard_label = QtWidgets.QLabel(self.maintab)
        self.nowcard_label.setGeometry(QtCore.QRect(70, 170, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.nowcard_label.setFont(font)
        self.nowcard_label.setObjectName("nowcard_label")
        self.nowcard_show = QtWidgets.QLabel(self.maintab)
        self.nowcard_show.setGeometry(QtCore.QRect(130, 170, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.nowcard_show.setFont(font)
        self.nowcard_show.setObjectName("nowcard_show")
        self.btn_radcard = QtWidgets.QPushButton(self.maintab)
        self.btn_radcard.setGeometry(QtCore.QRect(70, 210, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_radcard.setFont(font)
        self.btn_radcard.setObjectName("btn_radcard")
        self.btn_dealcard = QtWidgets.QPushButton(self.maintab)
        self.btn_dealcard.setGeometry(QtCore.QRect(200, 210, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_dealcard.setFont(font)
        self.btn_dealcard.setObjectName("btn_dealcard")
        self.pic_show = QtWidgets.QLabel(self.maintab)
        self.pic_show.setGeometry(QtCore.QRect(430, 50, 151, 171))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pic_show.setFont(font)
        self.pic_show.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pic_show.setObjectName("pic_show")
        self.pic_label = QtWidgets.QLabel(self.maintab)
        self.pic_label.setGeometry(QtCore.QRect(430, 250, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pic_label.setFont(font)
        self.pic_label.setObjectName("pic_label")
        self.title_label = QtWidgets.QLabel(self.maintab)
        self.title_label.setGeometry(QtCore.QRect(230, 10, 201, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.maintab)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 80, 113, 20))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.tabWidget.addTab(self.maintab, "")
        self.maintab2 = QtWidgets.QWidget()
        self.maintab2.setObjectName("maintab2")
        self.btn2_dealcard = QtWidgets.QPushButton(self.maintab2)
        self.btn2_dealcard.setGeometry(QtCore.QRect(200, 180, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn2_dealcard.setFont(font)
        self.btn2_dealcard.setObjectName("btn2_dealcard")
        self.btn_selectpic = QtWidgets.QPushButton(self.maintab2)
        self.btn_selectpic.setGeometry(QtCore.QRect(380, 240, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_selectpic.setFont(font)
        self.btn_selectpic.setObjectName("btn_selectpic")
        self.pic_show2 = QtWidgets.QLabel(self.maintab2)
        self.pic_show2.setGeometry(QtCore.QRect(350, 50, 151, 171))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pic_show2.setFont(font)
        self.pic_show2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pic_show2.setObjectName("pic_show2")
        self.btn2_readcard = QtWidgets.QPushButton(self.maintab2)
        self.btn2_readcard.setGeometry(QtCore.QRect(80, 180, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn2_readcard.setFont(font)
        self.btn2_readcard.setObjectName("btn2_readcard")
        self.title_label2 = QtWidgets.QLabel(self.maintab2)
        self.title_label2.setGeometry(QtCore.QRect(220, 10, 201, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.title_label2.setFont(font)
        self.title_label2.setObjectName("title_label2")
        self.nowcard_show2 = QtWidgets.QLabel(self.maintab2)
        self.nowcard_show2.setGeometry(QtCore.QRect(160, 150, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.nowcard_show2.setFont(font)
        self.nowcard_show2.setObjectName("nowcard_show2")
        self.nowcard_label2 = QtWidgets.QLabel(self.maintab2)
        self.nowcard_label2.setGeometry(QtCore.QRect(100, 150, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.nowcard_label2.setFont(font)
        self.nowcard_label2.setObjectName("nowcard_label2")
        self.name_label2 = QtWidgets.QLabel(self.maintab2)
        self.name_label2.setGeometry(QtCore.QRect(110, 80, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.name_label2.setFont(font)
        self.name_label2.setObjectName("name_label2")
        self.mobile_label2 = QtWidgets.QLabel(self.maintab2)
        self.mobile_label2.setGeometry(QtCore.QRect(80, 120, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mobile_label2.setFont(font)
        self.mobile_label2.setObjectName("mobile_label2")
        self.lineEdit = QtWidgets.QLineEdit(self.maintab2)
        self.lineEdit.setGeometry(QtCore.QRect(160, 80, 121, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.maintab2)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 120, 121, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.tabWidget.addTab(self.maintab2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name_labe1.setText(_translate("MainWindow", "姓名"))
        self.btn_find_name.setText(_translate("MainWindow", "查  找"))
        self.mobile_label.setText(_translate("MainWindow", "手机号码"))
        self.mobile_show.setText(_translate("MainWindow", "123"))
        self.precard_label.setText(_translate("MainWindow", "原卡号"))
        self.precard_show.setText(_translate("MainWindow", "123"))
        self.nowcard_label.setText(_translate("MainWindow", "现卡号"))
        self.nowcard_show.setText(_translate("MainWindow", ""))
        self.btn_radcard.setText(_translate("MainWindow", "读   卡"))
        self.btn_dealcard.setText(_translate("MainWindow", "制  卡"))
        self.pic_show.setText(_translate("MainWindow", "123"))
        self.pic_label.setText(_translate("MainWindow", "123"))
        self.title_label.setText(_translate("MainWindow", "金尚美食补卡模式"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.maintab), _translate("MainWindow", "Tab 1"))
        self.btn2_dealcard.setText(_translate("MainWindow", "制  卡"))
        self.btn_selectpic.setText(_translate("MainWindow", "选择照片"))
        self.pic_show2.setText(_translate("MainWindow", "123"))
        self.btn2_readcard.setText(_translate("MainWindow", "读   卡"))
        self.title_label2.setText(_translate("MainWindow", "金尚美食发卡模式"))
        self.nowcard_show2.setText(_translate("MainWindow", "123"))
        self.nowcard_label2.setText(_translate("MainWindow", "现卡号"))
        self.name_label2.setText(_translate("MainWindow", "姓名"))
        self.mobile_label2.setText(_translate("MainWindow", "手机号码"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.maintab2), _translate("MainWindow", "Tab 2"))

